# Generated by Django 6.0.2 on 2026-02-04 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=500)),
                ('google_book_id', models.CharField(max_length=100)),
                ('poster_url', models.URLField(blank=True, default='https://via.placeholder.com/150x200?text=No+Cover', max_length=500)),
                ('total_pages', models.PositiveIntegerField(default=0)),
                ('current_page', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('reading', 'reading'), ('completed', 'completed'), ('want-to-read', 'want-to-read')], default='want-to-read', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('google_book_id', 'user'), name='unique_google_book_per_user')],
            },
        ),
    ]
